# Generated by Django 4.2.3 on 2023-08-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_Title', models.CharField(max_length=50)),
                ('Task_Description', models.TextField()),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
    ]
